[theme]
base = "dark"
primaryColor = "#ff4b4b"
backgroundColor = "#121212"
secondaryBackgroundColor = "#1e1e1e"
textColor = "#e0e0e0"
font = "sans serif"

[server]
enableStaticServing = true

[browser]
gatherUsageStats = false